server:
  port: 8080
  servlet:
    context-path: /api
# 数据库配置
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zcomturtle?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

# swagger 接口文档
knife4j:
  enable: true
  openapi:
    title: 玛巴的接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.zcom.zcomturtle.controller


